language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x

os:
  - linux
  - osx

install:
  - "wget https://github.com/DataDog/zstd/files/2246767/mr.zip"
  - "unzip mr.zip"
script:
  - "go build"
  - "PAYLOAD=`pwd`/mr go test -v"
  - "PAYLOAD=`pwd`/mr go test -bench ."
